language: haskell
before_install:
  - CVC4=cvc4-20$(date -v-1d +"%y-%m-%d")-i386-linux-opt
  - wget http://cvc4.cs.nyu.edu/builds/i386-linux-opt/unstable/$CVC4
  - sudo mv $CVC4 /usr/local/bin/cvc4
  - sudo chmod a+x /usr/local/bin/cvc4
  - cvc4 --version
install:
  - cabal install alex
  - cabal install happy
script:
  - make test
ghc:
  - 7.6.3
  - 7.8.3

