language: haskell
before_install:
- CVC4=cvc4-2014-11-22-i386-linux-opt
- wget www.galois.com/~leepike/$CVC4
- sudo mv $CVC4 /usr/local/bin/cvc4
- sudo chmod a+x /usr/local/bin/cvc4
- cvc4 --version
install:
- cabal install alex happy
script:
- make test
ghc:
- 7.6
- 7.8
notifications:
  slack:
    secure: IQnBCQNqSYIoHv9c668lpWTnJHCWhVTLLcdxIPFFxpiyoPQQO1JPhFHLdyhB2T/W4b7mVeU1X32PJ1jRDHVEbMTcPGoBS1lstI7avTkeDQ1b8ILut6GnjmaGWWpCYimoWgAZeM1IBdfJ6jbDA861sQkSnJEb79UidLE8xyRkXAk=
