language: haskell

# IF you want to get the latest build,
# on a BSD machine, you'll want to use the following
# CVC4=cvc4-20$(date -v-1d +"%y-%m-%d")-i386-linux-opt
# On a GNU machine, use
# CVC4=cvc4-20$(date --date='1 day ago' +"%y-%m-%d")-i386-linux-opt
# Original URL: http://cvc4.cs.nyu.edu/builds/i386-linux-opt/unstable/$CVC4

before_install:
  - CVC4=cvc4-2014-11-22-i386-linux-opt
  - wget www.galois.com/~leepike/$CVC4
  - mv $CVC4 cvc4
  - export PATH=$PATH:./
  - chmod u+x cvc4
  - cvc4 --version
install:
  - cabal install alex
  - cabal install happy
script:
  - make test-compile
ghc:
  - 7.6
  - 7.8

# Allow (faster) Docker builds
sudo: false
