sudo: false
language: haskell
before_install:
- CVC4=cvc4-2014-11-22-i386-linux-opt
- mkdir -p bin
- wget http://www.galois.com/~leepike/$CVC4 -O bin/cvc4
- chmod a+x bin/cvc4
- PATH="$PWD/bin:$PATH"
- cvc4 --version
install:
- cabal install alex happy
script:
- make test
ghc:
- 7.6
- 7.8
notifications:
  slack:
    secure: IQnBCQNqSYIoHv9c668lpWTnJHCWhVTLLcdxIPFFxpiyoPQQO1JPhFHLdyhB2T/W4b7mVeU1X32PJ1jRDHVEbMTcPGoBS1lstI7avTkeDQ1b8ILut6GnjmaGWWpCYimoWgAZeM1IBdfJ6jbDA861sQkSnJEb79UidLE8xyRkXAk=
    secure: AcS89vo55VciqY8nSD8KWrAuMfTnKqJmbthYNaAfoqiVqXTi4PJaFriWNshjjxRTkzi+N9/qSv+iVXVC4jGX53ALb+JZHkQHCyYj8pU4Ce9xaGzXkmRQ6N6MmpARoNXrqh9Z+oJJsni5OQefh6EgKopJW5sXDTGlutezf0QsmNw=
